package com.goku.druid.demo.mapper;

import com.goku.druid.demo.model.gokuBussiness;
import com.goku.druid.demo.model.gokuBussinessKey;

public interface gokuBussinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_bussiness
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(gokuBussinessKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_bussiness
     *
     * @mbg.generated
     */
    int insert(gokuBussiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_bussiness
     *
     * @mbg.generated
     */
    int insertSelective(gokuBussiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_bussiness
     *
     * @mbg.generated
     */
    gokuBussiness selectByPrimaryKey(gokuBussinessKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_bussiness
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(gokuBussiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_bussiness
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(gokuBussiness record);
}