package com.goku.druid.demo.mapper;

import com.goku.druid.demo.model.gokuUserinfo;

public interface gokuUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_userinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_userinfo
     *
     * @mbg.generated
     */
    int insert(gokuUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_userinfo
     *
     * @mbg.generated
     */
    int insertSelective(gokuUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_userinfo
     *
     * @mbg.generated
     */
    gokuUserinfo selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_userinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(gokuUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_userinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(gokuUserinfo record);
}