package com.goku.druid.demo.mapper;

import com.goku.druid.demo.model.gokuTranlog;
import com.goku.druid.demo.model.gokuTranlogWithBLOBs;

public interface gokuTranlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_tranlog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_tranlog
     *
     * @mbg.generated
     */
    int insert(gokuTranlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_tranlog
     *
     * @mbg.generated
     */
    int insertSelective(gokuTranlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_tranlog
     *
     * @mbg.generated
     */
    gokuTranlogWithBLOBs selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_tranlog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(gokuTranlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_tranlog
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(gokuTranlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_tranlog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(gokuTranlog record);
}