package com.goku.druid.demo.mapper;

import com.goku.druid.demo.model.gokuAuthority;
import com.goku.druid.demo.model.gokuAuthorityKey;

public interface gokuAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_authority
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(gokuAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_authority
     *
     * @mbg.generated
     */
    int insert(gokuAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_authority
     *
     * @mbg.generated
     */
    int insertSelective(gokuAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_authority
     *
     * @mbg.generated
     */
    gokuAuthority selectByPrimaryKey(gokuAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(gokuAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(gokuAuthority record);
}