package com.goku.druid.demo.mapper;

import com.goku.druid.demo.model.gokuIpList;

public interface gokuIpListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_iplist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String ipaddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_iplist
     *
     * @mbg.generated
     */
    int insert(gokuIpList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_iplist
     *
     * @mbg.generated
     */
    int insertSelective(gokuIpList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_iplist
     *
     * @mbg.generated
     */
    gokuIpList selectByPrimaryKey(String ipaddress);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_iplist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(gokuIpList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goku_iplist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(gokuIpList record);
}