package com.goku.druid.demo.model;

public class FormElement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_element_.id_
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_element_.name_
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_element_.extra_properties_
     *
     * @mbg.generated
     */
    private String extraProperties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_element_.form_element_properties_
     *
     * @mbg.generated
     */
    private String formElementProperties;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_element_.multiple_
     *
     * @mbg.generated
     */
    private String multiple;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_element_.company_id_
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_element_.form_element_type_
     *
     * @mbg.generated
     */
    private Byte formElementType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_element_.form_template_id_
     *
     * @mbg.generated
     */
    private Integer formTemplateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_element_.id_
     *
     * @return the value of form_element_.id_
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_element_.id_
     *
     * @param id the value for form_element_.id_
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_element_.name_
     *
     * @return the value of form_element_.name_
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_element_.name_
     *
     * @param name the value for form_element_.name_
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_element_.extra_properties_
     *
     * @return the value of form_element_.extra_properties_
     *
     * @mbg.generated
     */
    public String getExtraProperties() {
        return extraProperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_element_.extra_properties_
     *
     * @param extraProperties the value for form_element_.extra_properties_
     *
     * @mbg.generated
     */
    public void setExtraProperties(String extraProperties) {
        this.extraProperties = extraProperties == null ? null : extraProperties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_element_.form_element_properties_
     *
     * @return the value of form_element_.form_element_properties_
     *
     * @mbg.generated
     */
    public String getFormElementProperties() {
        return formElementProperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_element_.form_element_properties_
     *
     * @param formElementProperties the value for form_element_.form_element_properties_
     *
     * @mbg.generated
     */
    public void setFormElementProperties(String formElementProperties) {
        this.formElementProperties = formElementProperties == null ? null : formElementProperties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_element_.multiple_
     *
     * @return the value of form_element_.multiple_
     *
     * @mbg.generated
     */
    public String getMultiple() {
        return multiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_element_.multiple_
     *
     * @param multiple the value for form_element_.multiple_
     *
     * @mbg.generated
     */
    public void setMultiple(String multiple) {
        this.multiple = multiple == null ? null : multiple.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_element_.company_id_
     *
     * @return the value of form_element_.company_id_
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_element_.company_id_
     *
     * @param companyId the value for form_element_.company_id_
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_element_.form_element_type_
     *
     * @return the value of form_element_.form_element_type_
     *
     * @mbg.generated
     */
    public Byte getFormElementType() {
        return formElementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_element_.form_element_type_
     *
     * @param formElementType the value for form_element_.form_element_type_
     *
     * @mbg.generated
     */
    public void setFormElementType(Byte formElementType) {
        this.formElementType = formElementType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_element_.form_template_id_
     *
     * @return the value of form_element_.form_template_id_
     *
     * @mbg.generated
     */
    public Integer getFormTemplateId() {
        return formTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_element_.form_template_id_
     *
     * @param formTemplateId the value for form_element_.form_template_id_
     *
     * @mbg.generated
     */
    public void setFormTemplateId(Integer formTemplateId) {
        this.formTemplateId = formTemplateId;
    }
}